name: Run tests

on: [push]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest

    name: Run tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: php-8.2-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Install dependencies
        run: |
           composer install --no-interaction
           composer update --prefer-dist --no-interaction

      - name: Execute tests
        run: ./vendor/bin/phpunit
